# .github/workflows/pages.yml
permissions:
  contents: write    # Needed so GITHUB_TOKEN can push commits
  pages: write       # Needed for deploy-pages step
  id-token: write    # (only if you use actions/deploy-pages@v1)

name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
